mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('stories/', include('stories.urls', namespace='stories')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from . import views
from django.urls import path

app_name = 'polls'  # now you have to add `polls:` to links
urlpatterns = [
    path('about', views.about, name='about'),
    # manual # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('index_long', views.index_long, name='index_long'),
    # ex: /polls/5/
    # manual # path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    # manual # path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    # manual # path('<int:question_id>/vote/', views.vote, name='vote'),
]

stories/urls.py
from django.urls import path
from . import views
from .feeds import LatestStoriesFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.story_list, name='story_list'),
    # path('', views.StoryListView.as_view(), name='story_list'),
    path('tag/<slug:tag_slug>/', views.story_list, name='story_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:story>/',
        views.story_detail,
        name='story_detail'),
    path('<int:story_id>/share/', views.story_share, name='story_share'),
    path('feed/', LatestStoriesFeed(), name='story_feed'),
]

stories/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

class LiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='live')


class Story(models.Model):
    STATUS_CHOICES = (
        ('empty', 'Empty'),
        ('draft', 'Draft'),
        ('live', 'Live'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='stories')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='empty')

    stories = models.Manager() # The default manager.
    liveStories = LiveManager() # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('stories:story_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])

class Comment(models.Model):
    story = models.ForeignKey(Story,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.story}'

stories/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from .models import Story, Comment
# from .forms import EmailStoryForm, CommentForm
from django import forms
from taggit.models import Tag

class EmailStoryForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

def story_list(request):
    object_list = Story.liveStories.all()
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        stories = paginator.page(page)
    except PageNotAnInteger:
        stories = paginator.page(1)
    except EmptyPage:
        stories = paginator.page(paginator.num_pages)
    return render(request,
                 'stories/story/list.html',
                 {'page': page,
                  'stories': stories})


def story_detail(request, year, month, day, story):
    story = get_object_or_404(Story, slug=story,
                                   status='live',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # List of active comments for this story
    comments = story.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            new_comment.story = story
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar stories
    story_tags_ids = story.tags.values_list('id', flat=True)
    similar_stories = Story.liveStories.filter(tags__in=story_tags_ids)\
                                  .exclude(id=story.id)
    similar_stories = similar_stories.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags','-publish')[:4]

    return render(request,
                  'stories/story/detail.html',
                  {'story': story,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_stories': similar_stories})


class StoryListView(ListView):
    queryset = Story.liveStories.all()
    context_object_name = 'stories'
    paginate_by = 3
    template_name = 'stories/story/list.html'

def story_share(request, story_id):
    story = get_object_or_404(Story, id=story_id, status='live')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailStoryForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            story_url = request.build_absolute_uri(story.get_absolute_url())
            subject = f"{cd['name']} recommends you read {story.title}"
            message = f"Read {story.title} at {story_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:
        form = EmailStoryForm()
    return render(request, 'stories/story/share.html', {'story': story,
                                                    'form': form,
                                                    'sent': sent})

stories/templates/stories/story/detail.html
{% extends "stories/base.html" %}
{% load stories_tags %}

{% block title %}{{ story.title }}{% endblock %}

{% block content %}
  <h1>{{ story.title }}</h1>
  <p class="date">
    Published {{ story.publish }} by {{ story.author }}
  </p>
  {{ story.body|markdown }}
  <p>
  <a href="{% url "stories:story_share" story.id %}">
    Share this story
  </a>
</p>
<h2>Similar Stories</h2>
{% for story in similar_stories %}
  <p>
    <a href="{{ story.get_absolute_url }}">{{ story.title }}</a>
  </p>
{% empty %}
  There are no similar stories yet.
{% endfor %}
{% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}
  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
    </form>
  {% endif %}
{% endblock %}

stories/templates/stories/story/latest_stories.html
{% load stories_tags %}
<ul>
  {% for story in latest_stories %}
    <li>
      <a href="{{ story.get_absolute_url }}">{{ story.title }}</a>
    </li>
  {% endfor %}
</ul>

stories/templates/stories/story/list.html
{% extends "stories/base.html" %}
{% load stories_tags %}

{% block title %}My Stories{% endblock %}

{% block content %}
  <h1>My Stories</h1>
  {% for story in stories %}
    <h2>
      <a href="{{ story.get_absolute_url }}">
        {{ story.title }}
      </a>
    </h2>
    <p class="tags">
    Tags:
    {% for tag in story.tags.all %}
      <a href="{% url "stories:story_list_by_tag" tag.slug %}">
        {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>
    <p class="date">
      Published {{ story.publish }} by {{ story.author }}
    </p>
    {{ story.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=page_obj %}
{% endblock %}

stories/templates/stories/story/share.html
{% extends "stories/base.html" %}
{% load stories_tags %}

{% block title %}Share a story{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ story.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ story.title }}" by e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}